version: 2

models:
  - name: example
    description: "Sales transactions"
    columns:
      - name: id
        description: "Primary key"
      - name: date
        description: "Sale date"
      - name: product
        description: "Product name"
      - name: region
        description: "Sales region"
      - name: amount
        description: "Sale amount in dollars"
        meta:
          metrics:
            total_revenue:
              type: sum
            average_sale:
              type: average
      - name: quantity
        description: "Units sold"
        meta:
          metrics:
            total_units:
              type: sum
